name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1
    - name: Build
      run: zig build --release=small
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          ./zig-out/bin/*.exe
          ./*.md

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - name: Download
      id: download
      uses: actions/download-artifact@v6
      with:
        path: im-status-${{ steps.version.outputs.version }}
    - name: Archive
      run: >
        7z a ${{ steps.download.outputs.download-path }}.zip
        ${{ steps.download.outputs.download-path }}/artifact/zig-out/bin/*.exe
        ${{ steps.download.outputs.download-path }}/artifact/*.md
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.download.outputs.download-path }}.zip
          ${{ steps.download.outputs.download-path }}/artifact/zig-out/bin/*.exe
