name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
    - name: Build
      run: zig build --release=small
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          ${{ github.workspace }}/zig-out/bin/*.exe
          ./*.md

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get version
      id: version
      run:  echo ::set-output name=version::${GITHUB_REF#refs/tags/}
    - name: Download
      id: download
      uses: actions/download-artifact@v4
      with:
        path: im-status-${{ steps.version.outputs.version }}
    - name: Archive
      run: 7z a ${{ steps.download.outputs.download-path }}.zip ${{ steps.download.outputs.download-path }}/artifact/*
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: ${{ steps.download.outputs.download-path }}.zip
